### ISSUE TITLE
Version 1.3.3 doesn't compile with MSVC 2003

### ISSUE THREAD

**Issue by Jmbryan** [philsquared/Catch#589]
I'm using Catch in a legacy project that uses MSVC 2003. After updating Catch to v1.3.3 I now get these compiler errors:

error C2061: syntax error : identifier '__LINE__Var'
error C2072: 'catch_internal_Section' : initialization of a function
fatal error C1903: unable to recover from previous error(s); stopping compilation

It has something to do with the SECTION macro. The prior version of Catch was working great and I will revert back to that version for now. Here is the header info of the prior working version:

"Generated: 2013-02-19 08:44:57.311773"

**Comment by philsquared** [comment]
If the "prior version" was from 2013 then, well, a lot has changed in the last three years!

In any case the line that would be causing your error is:
```
        if( Catch::Section const& INTERNAL_CATCH_UNIQUE_NAME( catch_internal_Section ) = Catch::SectionInfo( CATCH_INTERNAL_LINEINFO, name, desc ) )
```
where `INTERNAL_CATCH_UNIQUE_NAME` just appends the line number to the identifier it is passed. I don't believe this part has really changed since the start.

From your error message it does look like `__LINE__` is not being expanded correctly - nor is it being pasted with the root identifier. I don't know why this might be.

I don't have access to a VS2003 compiler to test it with, but you might want to experiment, outside of Catch, reproducing the `INTERNAL_CATCH_UNIQUE_NAME` macro to see how it behaves (it's actually a set of three macros).

**Comment by onqtam** [comment]
I think I've hit this same issue - but with VC++6 - see [here](http://stackoverflow.com/questions/36940730/preprocessor-problems-with-vc6)

This was my conclusion:

```
this turned out to be a compiler bug.
Turning off Edit and Continue from the debug info fixed the problem (the /ZI command line option)
```

**Comment by horenmar** [comment]
Unless turning off edit and continue doesn't help with VS2003, I am going to close this soon.

**Comment by philsquared** [comment]
I think we can close this now. If @Jmbryan or @onqtam (or anyone else) still have issues with it feel free to reopen (preferably with more details).
