### ISSUE TITLE
Doesn't compile on Travis

### ISSUE THREAD

**Issue by blerest** [philsquared/Catch#535]
Catch doesn't compile with Travis (clang-3.4). 

```
$ export CXX=clang++
$ export CC=clang
$ clang --version
clang version 3.4 (tags/RELEASE_34/final)
clang++ -W -Wall -Werror -Wunused-value -g -std=c++0x   -c -o test/test.o test/test.cpp
test/catch.hpp:1146:68: error: no type named 'underlying_type' in namespace
      'std'
  ...static_cast<typename std::underlying_type<T>::type>(v)
                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
test/catch.hpp:1146:62: error: expected '>'
                                         static_cast<typename std::under...
                                                             ^
test/catch.hpp:1146:53: note: to match this '<'
                                         static_cast<typename std::under...
                                                    ^
test/catch.hpp:1146:84: error: 'T' does not refer to a value
  ...static_cast<typename std::underlying_type<T>::type>(v)
                                               ^
test/catch.hpp:1140:27: note: declared here
        template<typename T>
                          ^
test/catch.hpp:1146:88: error: no member named 'type' in the global namespace
  ...static_cast<typename std::underlying_type<T>::type>(v)
                                                 ~~^
4 errors generated.
The command "./configure && make && make test" exited with 2.
Done. Your build exited with 1.
```

**Comment by Darelbi** [comment]
Afaik CATCH compiles perfectly on travis:
https://travis-ci.org/Darelbi/Infectorpp2/jobs/86167451

clang version:
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by nabijaczleweli** [comment]
@LOLKFC try using `clang-3.5` with the exact same configuration, smells to me like a too old of a  compiler (`-std=c++0x`).

**Comment by philsquared** [comment]
@blerest - are you still seeing this issue?

**Comment by blerest** [comment]
I fixed this issue using `clang-3.5`.

**Comment by philsquared** [comment]
Thanks
