### ISSUE TITLE
v2.0.0-develop.2 fails to compile with test on macOS/clang where v<=1.10.0 works

### ISSUE THREAD

**Issue by Property404** [philsquared/Catch#1009]
## Description
Trying to compile my unit test (see [here](https://github.com/Property404/fetlang/blob/master/fetishes/core/tests/chain.cpp))(NSFW) fails on, I'm guessing, trying to compare a FILE* to NULL (line 40 of linked unit test). I can use 1.10.0 and 1.9.7 just fine.  

I'm on macOS Sierra 10.12.6 with Clang(Apple LLVM version 8.1.0 (clang-802.0.42)),
building [Fetlang](https://github.com/Property404/fetlang)(NSFW) normally(`meson src build;cd build;ninja`)

Here are the results:
```
[61/72] Compiling Cpp object 'unit_tests@exe/.._fetishes_core_tests_chain.cpp.o'.
FAILED: unit_tests@exe/.._fetishes_core_tests_chain.cpp.o           
c++  -Iunit_tests@exe -I. -I../src -I../fetishes -I../src/../fetishes -I../src/thirdparty/boost/ -I../src/thirdparty -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -MMD -MQ 'unit_tests@exe/.._fetishes_core_tests_chain.cpp.o' -MF 'unit_tests@exe/.._fetishes_core_tests_chain.cpp.o.d' -o 'unit_tests@exe/.._fetishes_core_tests_chain.cpp.o' -c ../fetishes/core/tests/chain.cpp
In file included from ../fetishes/core/tests/chain.cpp:1:           
../src/thirdparty/catch.hpp:918:96: error: comparison between pointer and integer ('__sFILE *' and 'long')                               
    auto compareEqual( LhsT const& lhs, RhsT&& rhs ) -> bool { return const_cast<LhsT&>( lhs ) == rhs; };                                
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~                                    
../src/thirdparty/catch.hpp:939:45: note: in instantiation of function template specialization 'Catch::compareEqual<__sFILE *, long &>' requested here
            return BinaryExpr<LhsT, RhsT&>( compareEqual( m_lhs, rhs ), m_lhs, "==", rhs );                                              
                                            ^                       
../fetishes/core/tests/chain.cpp:40:24: note: in instantiation of function template specialization 'Catch::ExprLhs<__sFILE *&>::operator==<long>' requested here
                REQUIRE_FALSE(stream == NULL);      
```

### Steps to reproduce
```Shell
$ git clone https://github.com/Property404/fetlang
$ cd fetlang
$ cd src/thirdparty
$ rm catch.hpp
$ wget https://github.com/philsquared/Catch/releases/download/v2.0.0-develop.2/catch.hpp
$ cd -
$ meson src build
$ cd build
$ ninja
$ # fails here
```

### Extra information
* Catch version: **v2.0.0-develop.2**
* Operating System: **macOS 10.12.6**
* Compiler+version: **Apple LLVM version 8.1.0 (clang-802.0.42)**

**Comment by horenmar** [comment]
The rewritten decompose + evaluation layer were missing handling of `NULL` defined as `long`.

**Comment by horenmar** [comment]
Should be fixed in dev 3 (just released)
