### ISSUE TITLE
uint64_t is not defined for VS 2010

### ISSUE THREAD

**Issue by grahamshanks** [philsquared/Catch#894]
## Description

After updating from v1.9.1 to v1.92 there is a compilation error under VS 2010 in catch (function getCurrentTicks in catch_timer.hpp). The reason is that uint64_t is not defined.

* Catch version: **v1.9.2**
* Operating System: **Windows 7**
* Compiler+version: **Visual Studio 2010**

### Workaround (possible fix)

Include `<cstdint>` in  catch_timer.hpp

**Comment by philsquared** [comment]
Thanks for bringing this up - looks like I missed some references. I think I've got them all now - but I don't have access to VS2010 for a while to check so please let me know if 1.9.3 fixes it for you?

**Comment by grahamshanks** [comment]
Confirmed as fixed on VS2010 as well as VS2008, VS2013 and VS2015
